services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalpa-vue-app
    command: pnpm dev --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store

volumes:
  node_modules:
  pnpm_store:
